server:
  port: 9191
  
spring:
  application:
    name: ORDER-SERVICE
  
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
    serviceUrl:
     defaultzone: http://localhost:8761/eureka/
instance:
  hostname: localhost